### ISSUE TITLE
auto removes " " in compose file while deploying the stack

### ISSUE THREAD

**Issue by shreehari1** [louislam/dockge#118]
have a application which requires "" while defining volumes. it removes the "/data:/dada" -> /data:/data and container fails to deploy

**Comment by louislam** [comment]
Can you show the example of that path?

**Comment by shreehari1** [comment]
`volumes:
      - "./navidrome:/data"

volumes:
      - "./photoprism/Pictures:/photoprism/originals" `

documentation has " " mentioned and some of the apps dont use " " so they work fine

**Comment by louislam** [comment]
Cannot reproduce, my stack is able to start without any errors using your volumes

What is the error msg?

**Comment by shreehari1** [comment]
I did some digging from my side too. looks like there is some issue with the image i was trying. I am not facing it on there images.
Loving the project, waiting for more things coming up. all the best.

**Comment by zebulun78** [comment]
This is still a problem.  I have an image that requires the quotes to remain, and dockge is stripping the quotes from my compose file...

**Comment by zebulun78** [comment]
The quotes get stripped when you go to edit the compose file, even though it saves them properly the first time

**Comment by radh21301** [comment]
I have the exact same issue as @zebulun78

**Comment by bverkron** [comment]
I have the same issue. Why was this closed?
