### ISSUE TITLE
Dockge UI is not being showed (blank screen)

### ISSUE THREAD

**Issue by edersong** [louislam/dockge#169]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Without any environmental changes, the dockge UI is not being showed anymore.

![image](https://github.com/louislam/dockge/assets/64137913/266adb6e-934f-4e29-bc85-0ab2d2ab4d41)

### 👟 Reproduction steps

- Tried clearing cookies
- Tried another browser
- Tried another machine
- Tried restarting container
- Tried recreating dockge container
- No issues were found on the dockge logs
- DNS and Proxy working fine
- All other containers are running fine.

### 👀 Expected behavior

Open the dockge UI

### 😓 Actual Behavior

Dockge UI is not being showed. Blank screen.

### Dockge Version

1.1.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome Version 119.0.6045.160 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 24.0.7

### 🟩 NodeJS Version

N/A

### 📝 Relevant log output

```shell
2023-11-24T11:01:48Z [SERVER] INFO: Welcome to dockge!
2023-11-24T11:01:48Z [SERVER] INFO: NODE_ENV: production
2023-11-24T11:01:48Z [SERVER] INFO: Data Dir: ./data/
2023-11-24T11:01:48Z [SERVER] INFO: Server Type: HTTP
2023-11-24T11:01:48Z [DB] INFO: Database Type: sqlite
2023-11-24T11:01:48Z [SERVER] INFO: Connected to the database
2023-11-24T11:01:48Z [SERVER] INFO: Listening on 5001
```

**Comment by louislam** [comment]
Any special config like a reverse proxy?

Also try to right click and view source in the page.

**Comment by edersong** [comment]
None, just a basic configuration for NGINX.
Strangely, opened the Dockge to go to view source and it worked fine 🤔
Will monitor for some additional days.

**Comment by kaywoz** [comment]
Same experience here with simply a blank page after som days of it working, setup is behind a cloudflare tunnel.

I'll respond back when/if it happens again with some more data. Simply brought down the stack and restarted the container and it worked in the browser immediately.

**Comment by tippfehlr** [comment]
Experienced this seemingly random. Restarting dockge via ssh always resolved the issue.
Accessed via local network, no proxy, no ssl
![image](https://github.com/louislam/dockge/assets/46620049/6cf3798e-a04e-4b89-9eaa-00f34ece5481)

**Comment by tippfehlr** [comment]
just happened to me after reloading the web page while on `http://dockge.local/compose/xxx`
trying to access any page then results in above result

**Comment by louislam** [comment]
Ops, just happened to me too, it is actually related to #145. I think I can reproduce.
