### ISSUE TITLE
Folders without compose config visible in UI

### ISSUE THREAD

**Issue by ToshY** [louislam/dockge#183]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

After #9 was fixed,  Dockge will now startup even if mounted directory has folders without compose config files. However, Dockge will still show these folders in the UI.

![image](https://github.com/louislam/dockge/assets/31921460/edafc3d4-160a-4aee-9e87-dfbc37db536f)

### 👟 Reproduction steps

1. Add a folder without a `compose.yaml` file in the the mounted directory.
2. Up dockge.
3. See the unwanted folder in the sidebar.

### 👀 Expected behavior

Not showing folders(/files) that are irrelevant for Dockge; if it does not contain a compose configuration file, it should not show up.

### 😓 Actual Behavior

![image](https://github.com/louislam/dockge/assets/31921460/edafc3d4-160a-4aee-9e87-dfbc37db536f)

### Dockge Version

1.1.1-nightly-20231125142720

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Google Chrome 119.0.6045.160 

### 🐋 Docker Version

24.0.5

**Comment by csjewell** [comment]
I was just going to suggest ignoring .git directories (because I commit my stack into a git repository) but this is more general.

Maybe have a 'ignore this directory' option (and make .* ignored by default?)

**Comment by MrNavaStar** [comment]
Maybe a combination of ignoring `.*` files and also checking for the presence of a compose.yaml?

**Comment by MrNavaStar** [comment]
My only worry with validating the files is that it will probably slow down on large setups. I believe the files are walked through on every page reload, so I imagine it would cause some noticeable lag when opening the page.

**Comment by Ozy-Viking** [comment]
I am checking for any of: `docker-compose.{yml,yaml}` or  `compose.{yml,yaml}`.

**Comment by quantumfrost** [comment]
> I am checking for any of: `docker-compose.{yml,yaml}` or `compose.{yml,yaml}`. My approach was asserting that any of the 4 file exists then if it errors it returns `false` otherwise returns `true`. In essence `O(4n)` compared to the original `O(n)` .

Another common pattern is to use a `project_name.{yml,yaml}` file, like `dockge/dockge.yaml` and then launch with `docker compose -f` option. Could that be supported too?
