### ISSUE TITLE
Octoprint container creating a new entry when running, showing as "not managed by Dockge"

### ISSUE THREAD

**Issue by larsinka** [louislam/dockge#196]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I moved my two octoprint stacks into the stacks folder and run them via the web interface, however upon start they create a new entry in the sidebar which is faded out and shows "This stack is not managed by Dockge." The original entry stays on "inactive"

### 👟 Reproduction steps

1. Move existing octoprint stack to the stacks folder (maybe also works with new stack)
2. Run via web interface

### 👀 Expected behavior

Only one entry on sidebar which shows the stack as "running" and lets me stop, update and restart.

### 😓 Actual Behavior

"Inactive" entry stays, another entry shows up which states the container is not managed by Dockge.

### Dockge Version

1.1.1

### 💻 Operating System and Arch

Proxmox VE 8.1.3 x86_64

### 🌐 Browser

Safari (MacOS)

### 🟩 NodeJS Version

20.10.24+dfsg1

### 📝 Relevant log output

```shell
"This stack is not managed by Dockge."
```

**Comment by louislam** [comment]
I did move some of my stacks before, I haven't seen this. The faded out item usually means that the compose file is not stacks directory 

You can check if the stack is running under the "stacks" directory: `docker compose ls`

**Comment by larsinka** [comment]
I found the problem. Stack-folder name was "octoMk3", had to change it to "octomk3" .. took me a while to remember that only small letters are allowed.
