### ISSUE TITLE
Y/n inputs not allowed in console

### ISSUE THREAD

**Issue by lammetak** [louislam/dockge#203]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

For example if I use the command docker prune --all it will prompt me the question are you sure: y/N". I'm not allowed to send the command. Not sure it is a bug or by design as it is not listed in the top.

### 👟 Reproduction steps

docker prune --all from the command line

### 👀 Expected behavior

input y/n or yes/no

### 😓 Actual Behavior

Command not allowed

### Dockge Version

1.20

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
Duplicate of #127
