### ISSUE TITLE
Improve console layout width, avoid unnecessary new lines

### ISSUE THREAD

**Issue by Trainax** [louislam/dockge#223]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When executing some commands (like `docker ps`) in the console the width is not correctly optimized and unnecessary new lines are inserted in the output.

Example:

![immagine](https://github.com/louislam/dockge/assets/30187360/c6dc2c70-ff1c-4a20-8e74-32988c13f099)

Here we can see STATUS, PORTS and NAMES being on a new line

### 👟 Reproduction steps

1. Open the console in Dockge
2. Launch a command which prints some long lines (like `docker ps`)
3. Observe the output containing unnecessary new lines

### 👀 Expected behavior

I would like the output to be like it is in the console via SSH, like this:

![immagine](https://github.com/louislam/dockge/assets/30187360/bec769fc-bcfe-4d5d-b2c4-a89ad5c90f6d)

### 😓 Actual Behavior

Unnecessary new lines are inserted even if there is enough space on the right in the console in Dockge

### Dockge Version

1.3.3

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

Mozilla Firefox version 120.0.1

### 🐋 Docker Version

Docker version 24.0.7, build afdd53b

**Comment by Trainax** [comment]
This behavior can also be observed in the terminal of the page dedicated to the single container where the line ends prematurely

![immagine](https://github.com/louislam/dockge/assets/30187360/ad3f8193-5ac4-44e8-8f64-0879f8e77c6d)

**Comment by Kareltje1980** [comment]
Loving the project, but I think this could be improved.

**Comment by Ozy-Viking** [comment]
It seems to be fixed to 488px, most likely a setting in xtermjs.

**Comment by Ozy-Viking** [comment]
I have created a pr #285 that solves it for each load of the screen but doesn't listen for the "resize" event. Added a todo for that in the jsdocs.

**Comment by Jadan1213** [comment]
I would love if it was also possible for the UI to allow editing the compose.yml in a fullscreen/widescreen format instead of being scrunched to the side. It would make it a lot easier to read when there's a lot in the file.

**Comment by louislam** [comment]
Fixed by https://github.com/louislam/dockge/pull/285
