### ISSUE TITLE
Error message when updating stacks with Dockge

### ISSUE THREAD

**Issue by Jayllyz** [louislam/dockge#236]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

![image](https://github.com/louislam/dockge/assets/16305216/335c95be-e6b3-4744-8886-e039afbc8b0c)
Even if the update has worked or there is no update, this error message appears.

### 👟 Reproduction steps

Press "update" button on any of your stacks.

### 👀 Expected behavior

A success message when an update has taken place and a message when there is nothing to update.

### 😓 Actual Behavior

Error message

### Dockge Version

1.3.1

### 💻 Operating System and Arch

Ubuntu 23.10

### 🌐 Browser

Google Chrome 119.0.6045.200

### 🐋 Docker Version

24.0.7

**Comment by louislam** [comment]
Should be fixed in 1.3.2.

**Comment by cirrusflyer** [comment]
I noticed 1.3.2 is gone?
