### ISSUE TITLE
Long .env file can't be fully edited.

### ISSUE THREAD

**Issue by mariushosting** [louislam/dockge#247]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

If you have a long .env file, you can only modify half of it.
![screencapture-192-168-1-18-5571-compose-firefly-2023-12-06-01_11_07](https://github.com/louislam/dockge/assets/37554361/0cc68108-d351-4de9-ab67-3330961ea027)

### 👟 Reproduction steps

upload a long .env file

### 👀 Expected behavior

expect to modify all lines.

### 😓 Actual Behavior

can't modify all env variables.

### Dockge Version

1.3.1

### 💻 Operating System and Arch

20.04

### 🌐 Browser

Chrome latest

**Comment by louislam** [comment]
> This is a problem with the .env highlighter and \r\n's I'll put in a fix for it @louislam

Thanks. Actually, Prismjs provides a hightlighter for `.ini`, not sure if it works with `.env`.

And #248, not sure if they are same issue.
