### ISSUE TITLE
Name of containers are not the same when starting with Dokge vs docker-compose

### ISSUE THREAD

**Issue by nzprog** [louislam/dockge#251]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When I run Dockge start container,  it will give a container name of 

-  CONTAINERNAME-SERVICE-1

but if I run the compose from docker-compose, I get   

- CONTAINERNAME_SERVICE_1   (Notice the _  instead of -  )

and because it's different nginx-proxy-manager doesn't find it.  

### 👟 Reproduction steps

In a terminal run:  watch -n 1 'docker inspect NETWORK_ID | grep CONTAINERNAME'
(To get a network id, I ran docker network ls | grep nginx-proxy-manager_default )

To start in docker-compose 

1. cd /opt/stacks/CONTAINERNAME
2. docker-compose up

then record the names in the watch are different from when it's created in Dockge.

### 👀 Expected behavior

When starting in Dockge, it should match docker-compose.   either pattern is ok,  I just want them to be the same so I can target services with the right name.

### 😓 Actual Behavior

The names of the services are different.   

### Dockge Version

1.1.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

### 🟩 NodeJS Version

v20.9.0

**Comment by louislam** [comment]
Because you are using compose v1, but Dockge built on top of docker compose v2

> In Compose V1, an underscore (_) was used as the word separator. In Compose V2, a hyphen (-) is used as the word separator.

https://docs.docker.com/compose/migrate/
