### ISSUE TITLE
Node taking 100% CPU

### ISSUE THREAD

**Issue by nzprog** [louislam/dockge#252]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Node will take 100% cpu after a while.
I believe after starting a container and clicking to other containers, makes the node process go crazy.   But it takes a while to build up cpu %
Because of this i have to check the cpu or kill the rouge process after interacting with Dockge
![image](https://github.com/louislam/dockge/assets/6001901/9ece8c7b-9b5c-4d24-8dd6-67cae2eb1351)

### 👟 Reproduction steps

Seems to happen after I start a terminal connection in Dockge and quickly switch to another container.  Or I could be wrong, not entirely sure.

### 👀 Expected behavior

it doesn't hang like that

### 😓 Actual Behavior

It hangs

### Dockge Version

1.1.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

### 🟩 NodeJS Version

v20.9.0

**Comment by louislam** [comment]
Fixed in previous version, please update.
