### ISSUE TITLE
Unnecessary new rows with line number

### ISSUE THREAD

**Issue by ChristianNik** [louislam/dockge#273]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

If the text is too long, it is wrapped and it looks as if it is a new line.

![grafik](https://github.com/louislam/dockge/assets/40700226/770e5149-5340-48dc-a473-b392faece0b2)

### 👟 Reproduction steps

Enter a long text into the compose file section.

### 👀 Expected behavior

Something like this:

![grafik](https://github.com/louislam/dockge/assets/40700226/e16b404d-75c0-4730-860c-57f56a507a4b)

Or with a scrollbar:

![grafik](https://github.com/louislam/dockge/assets/40700226/6d9c0c43-fbf2-4104-abd2-42d822124ddf)
![grafik](https://github.com/louislam/dockge/assets/40700226/c96a5153-d36b-483f-9557-86b358f60469)

### 😓 Actual Behavior

The text gets wrapped and it looks as if it is a new line.

### Dockge Version

1.3.3

### 💻 Operating System and Arch

x86_64 GNU/Linux

### 🌐 Browser

Firefox 120.0.1 (64-Bit)

**Comment by louislam** [comment]
Duplicate of #105
