### ISSUE TITLE
permission denied, mkdir '/opt/stacks'

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/dockge#28]
Getting this error when trying to start backend, i am using Gitpod as i my pc dont support Docker :(

![image](https://github.com/louislam/dockge/assets/53424436/1c2cab89-8c9c-411d-a7bb-590239cadd66)

**Comment by louislam** [comment]
Since I am developing this on Windows, I think you need to set `DOCKGE_STACKS_DIR=<your path>` at this moment.

**Comment by Zaid-maker** [comment]
> Since I am developing this on Windows, I think you need to set `DOCKGE_STACKS_DIR=<your path>` at this moment.
> 
> But I don't think gitpod could run `docker compose` commands either? Should develop it on your PC.

Ohhh so then i will give it a try on codespace.

**Comment by Zaid-maker** [comment]
Also just to remind u didn't make a release for 1.0.2 on release page and not 1.0.3

**Comment by louislam** [comment]
> Also just to remind u didn't make a release for 1.0.2 on release page and not 1.0.3

Forget to press release.😂
