### ISSUE TITLE
Having expose prevents contains from being listed

### ISSUE THREAD

**Issue by nzprog** [louislam/dockge#286]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When I expose a postgres port the Containers list is empty.  _(also labeled as existed when all containers are running)_
![image](https://github.com/louislam/dockge/assets/6001901/fb58ac02-6310-439f-9670-5e259f6f7250)

When I remove the expose,  it lists the containers.
![image](https://github.com/louislam/dockge/assets/6001901/82435acb-a57e-4c93-8ae7-15499d3d8fc8)

### 👟 Reproduction steps

Put a exposed port in the container.

### 👀 Expected behavior

It shouldn't fail to list the containers.
I dont know if it's related but noticed the Status says Exited when all containers are running/healthy.

### 😓 Actual Behavior

It doesn't display the container list.

### Dockge Version

1.3.3

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 24.0.7, build afdd53b

### 🟩 NodeJS Version

v20.9.0

**Comment by louislam** [comment]
It seems that the env update in 1.3.3 is not perfect.

Will try to fix it.

**Comment by louislam** [comment]
Fixed: #301
