### ISSUE TITLE
Line counter isn't working when lines wrap due to narrow screen sizes

### ISSUE THREAD

**Issue by jtenniswood** [louislam/dockge#305]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

<img width="105" alt="Screenshot 2023-12-16 at 16 39 35" src="https://github.com/louislam/dockge/assets/10881541/ddb0587e-06ea-4752-9fa1-bf9a962d1a7d">

When a line wraps, the line counter doesn't skip, so down the bottom, they don't align

### 👟 Reproduction steps

Look at a line wrap

### 👀 Expected behavior

Skip numbering lines that wrap

### 😓 Actual Behavior

Just counts the number of lines regardless of if they wrap.

### Dockge Version

1.3.4

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Safari

**Comment by louislam** [comment]
#105
