### ISSUE TITLE
Parsing error on lemmy's docker compose

### ISSUE THREAD

**Issue by P6g9YHK6** [louislam/dockge#335]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

![image](https://github.com/louislam/dockge/assets/17877371/b76d10b5-921b-4487-8101-ea53f9599fe7)

### 👟 Reproduction steps

follow https://join-lemmy.org/docs/administration/install_docker.html
and try to edit the files with dockge

### 👀 Expected behavior

Being able to edit the file

### 😓 Actual Behavior

file is displayed but not able to edit it

### Dockge Version

1.3.5

### 💻 Operating System and Arch

slackware 15

### 🌐 Browser

FF 121

### 🐋 Docker Version

20.10.24

### 📝 Relevant log output

```shell
2024-01-02T13:48:55Z [GETSERVICESTATUSLIST] ERROR: Error: Process exited with code 15
    at ChildProcess.done (/app/node_modules/.pnpm/promisify-child-process@4.1.2/node_modules/promisify-child-process/index.cjs:70:19)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 15,
  signal: null,
  stdout: '',
  stderr: 'parsing /boot/config/plugins/compose.manager/projects/lemmy/docker-compose.yml: yaml: line 32: found character that cannot start any token\n'
}
```

**Comment by louislam** [comment]
![image](https://github.com/louislam/dockge/assets/1336778/67c3d958-1065-49c3-a66a-8092722f29fb)

It is not a yaml file.

I think you should report to lemmy, because they do not generate the yaml correctly.
