### ISSUE TITLE
docker agent undefined IP issue

### ISSUE THREAD

**Issue by vishalkadam7** [louislam/dockge#337]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 👟 Reproduction steps

for testing the beta update in my localhost, I have added the agent ip from my cloud vm works fine but when a container is launched instead of giving the ip it opens as undefined 
for example - http://undefined:8081/

### 👀 Expected behavior

might be its not recognising the agent ip aaddress

### 😓 Actual Behavior

not sure

### Dockge Version

1.4.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

chrome

**Comment by louislam** [comment]
Ops, let me quick fix it.

**Comment by louislam** [comment]
1.4.1 has been released.

**Comment by vishalkadam7** [comment]
thanks its working now, I was wondering would it be possible to sync automatically instead of adding an agent, and an option to make master or worker to the one we required.
I think for this case advanced auth might required, and SSO would be better option
