### ISSUE TITLE
Login labels over each other

### ISSUE THREAD

**Issue by jicho** [louislam/dockge#347]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When I login I get the following with the labels in Safari:
![image](https://github.com/louislam/dockge/assets/610740/51647219-5a70-4e86-836f-c84657e3ea14)
For some reason they are overlapping... 

I think that I see the both Dutch (in my case) and English translation displayed both.

### 👟 Reproduction steps

Go to the login page with a translation and view the input fields without placing the focus on them.

### 👀 Expected behavior

See only one label :)

### 😓 Actual Behavior

I see two labels/placeholders in 1 input field.

Looking at the HTML source I think it has something to do with this:
```
<div data-v-e469ef08="" class="form-floating mt-3">
   <input data-v-e469ef08="" id="floatingPassword" type="password" class="form-control" placeholder="Password" autocomplete="current-password" required="">
   <label data-v-e469ef08="" for="floatingPassword">Wachtwoord</label>
</div>
```

You get the "Password" as a placeholder and a "Wachtwoord" (Dutch version of "Password") as a label.
I think the label is placed over the input field and that why I'm seeing both Dutch and English...

I guess that the problem is solved when the translation of the place holder is fixed or... when the placeholder is disabled or... when the label is only shown when the focus is on the field.

### Dockge Version

1.4.1

### 💻 Operating System and Arch

Synology NAS + Docker

### 🌐 Browser

Chrome 120.0.6099.199 / Safari 17.2.1 (19617.1.17.11.12)

### 🐋 Docker Version

Lastest version of Synology

**Comment by cyril59310** [comment]
I opened a pull request to fix this issue two days ago. #342

**Comment by louislam** [comment]
Closed by https://github.com/louislam/dockge/pull/342
