### ISSUE TITLE
Port stuck if host computer crashes

### ISSUE THREAD

**Issue by msrheidema** [louislam/dockge#353]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

If the host computer crashes and docker did not normally shut down the container NodeJS gets stuck in a loop where it can't start as it thinks the port is in use.

Rebooting the host does not fix the problem, only removing the container and recreating it.

### 👟 Reproduction steps

HALT the host computer (Power loss)

### 👀 Expected behavior

Start normally as the port is not held by anything

### 😓 Actual Behavior

Get stuck in a loop where the webserver can't start

### Dockge Version

1.4

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye)

### 🌐 Browser

Firefox osx 20.0.1

### 🐋 Docker Version

Docker version 20.10.21, build baeda1f

### 📝 Relevant log output

```shell
Node.js v18.17.1
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error: listen EADDRINUSE: address already in use /tmp/tsx-0/7.pipe
    at Server.setupListenHandle [as _listen2] (node:net:1734:21)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1898:5)
    at file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:53:31317
    at new Promise (<anonymous>)
    at yn (file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:53:31295)
    at async file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:55:459 {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '/tmp/tsx-0/7.pipe',
  port: -1
}
```

**Comment by cloning5480** [comment]
Changing the image tag from "louislam/dockge:1" to "louislam/dockge:1.4.1" got it to work again for me (using unraid template)

**Comment by fjimenezone** [comment]
I am experiencing the same effect. Every time I shutdown or reboot the server properly, afterwards I get dockge in a restarting loop with the same log messages.

```
Node.js v18.17.1
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^
Error: listen EADDRINUSE: address already in use /tmp/tsx-0/7.pipe
    at Server.setupListenHandle [as _listen2] (node:net:1734:21)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1898:5)
    at file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:53:31317
    at new Promise (<anonymous>)
    at yn (file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:53:31295)
    at async file:///pnpm/global/5/.pnpm/tsx@4.6.2/node_modules/tsx/dist/cli.mjs:55:459 {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '/tmp/tsx-0/7.pipe',
  port: -1
}
```

**Comment by x1ao4** [comment]
Same here.

**Comment by AmIBeingObtuse** [comment]
Glad this wasn't just me. Racking my brains out trying multiple ports. Only worked after deleting container and re deploying.

**Comment by louislam** [comment]
The error is thrown from tsx, which may be a upstream bug.

https://github.com/privatenumber/tsx/blob/985bbb8cff1f750ad02e299874e542b6f63495ef/src/utils/ipc/server.ts#L40

Let's see if I can reproduce with minimal steps.

**Comment by louislam** [comment]
Possibly Wordaround:

```
docker compose down
docker compose up
```

**Comment by AmIBeingObtuse** [comment]
```
docker compose down
docker compose up
```

Is this considered closed because we can down and up again? or is a permanent fix on the roadmap?

**Comment by louislam** [comment]
@AmIBeingObtuse No, I implemented a workaround, which deletes the tmp folder before start. See #380.

**Comment by AmIBeingObtuse** [comment]
Awesome thanks for the fast reply and workaround will test this soon.

**Comment by louislam** [comment]
> Awesome thanks for the fast reply and workaround will test this soon.

Thanks. You can try the `nightly` image:


```yaml
services:
  dockge:
    image: louislam/dockge:nightly  
```

PS: You should switch back to `1` when `1.4.2` is released.

**Comment by AmIBeingObtuse** [comment]
> > Awesome thanks for the fast reply and workaround will test this soon.
> 
> Thanks. You can try the `nightly` image:
> 
> ```yaml
> services:
>   dockge:
>     image: louislam/dockge:nightly  
> ```
> 
> PS: You should switch back to `1` when `1.4.2` is released.

Seems to be working perfectly.

Once again thank you for your fast turn around on this.

**Comment by bwirt** [comment]
Are you sure this is fixed?  I experienced this in 1.4.2 as well.  Taking the container down and back up fixed it.

**Comment by Zackptg5** [comment]
I'm having this bug now on nightly. New deployment on debian stable and can't get it to initialize at all

**Comment by bwirt** [comment]
This is still a problem.
