### ISSUE TITLE
This stack is not managed by Dockge.

### ISSUE THREAD

**Issue by markusglaetzner** [louislam/dockge#359]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I get a "This stack is not managed by Dockge." for all projects in the defined stack-folder. I also get error messages in the dockge container-log every 5 min (see down below). After creating a new compose of an existing project (with the same name), I get full functionality in dockge - I do not know what happens here...

### 👟 Reproduction steps

I can reproduce this behavior when I restore my docker vm.

### 👀 Expected behavior

Full functionality on all stack-projects.

### 😓 Actual Behavior

All stack-projects are "greyed out" and when I click on one, I get message "This stack is not managed by Dockge."

### Dockge Version

1.4.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

24.0.7

### 🟩 NodeJS Version

18.19.0

### 📝 Relevant log output

```shell
2024-01-09T18:07:29+01:00 [GETSERVICESTATUSLIST] ERROR: Error: spawn docker ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by louislam** [comment]
Docker spawn issue. Merge to #361.

**Comment by Dleewee** [comment]
> What is your directory structure in your stacks directory? Ex: /opt/stacks ├── ollama │   ├── compose.yaml │   └── ollama └── ollama-webui └── compose.yaml
> 
> To list your tree, `apt install tree`, then run `tree /opt/stacks -L 2`. (Update apt first and use your own dockge stacks directory if applicable.)

To add context here for anyone running into this issue - you cannot put your main "compose.yml" directly in the "base folder" which is setup as your stacks directory. You need to put in a sub-directory for Dockge to pick it up.
