### ISSUE TITLE
Security Issue (Arbitrary Code Execution)

### ISSUE THREAD

**Issue by 0xb1b1** [louislam/dockge#412]
DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/dockge/security/advisories/new.
^^^ This link is broken.

There is a huge security hole in the default configuration that should be disabled by default. Since there's no viable contact option available in either your patches or your profile, please contact me via email (you can find it in my patches, e.g. https://github.com/0xb1b1/nixos-config/commit/10e1c274a07422c56f59bb515ecf4b6af6f17185.patch).

Thanks!
-0xb1b1

**Comment by louislam** [comment]
The link has been fixed. You can report to it now. Thanks.

**Comment by Triskae** [comment]
Hello, Has the problem been solved ?

**Comment by dodgex** [comment]
The fact that there has been no commit or release since this issue exists lets assume the issue is not fixed yet.

**Comment by louislam** [comment]
No report from @0xb1b1  yet, feel free to re-open if the report will be submitted.
