### ISSUE TITLE
Cant paste command into terminal

### ISSUE THREAD

**Issue by vijay-prema** [louislam/dockge#419]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I open a bash terminal in the web interface for a container, I can type and run commands, as well as copy commands to system clipboard, but I cannot paste a command from system clipboard into the terminal in the web browser.

### 👟 Reproduction steps

1. Open bash terminal for any container in the web interface.
2. Typing commands works as normal
3. Pasting commands using ctrl+V or ctrl+shift+V do not work
4. Pasting via browser right click context menu and clicking paste does not work either

### 👀 Expected behavior

Using paste commands via keyboard shortcut and/or context menu should enter text into the terminal

### 😓 Actual Behavior

Nothing happens when using paste command

### Dockge Version

1.4.2

### 💻 Operating System and Arch

ubuntu 2204 x64

### 🌐 Browser

Firefox 1.2.2 64bit debian package

### 🐋 Docker Version

25.0.1

**Comment by louislam** [comment]
Duplicate of https://github.com/louislam/dockge/discussions/141
