### ISSUE TITLE
Can't paste text into the console

### ISSUE THREAD

**Issue by xhos** [louislam/dockge#470]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Can not paste any text into the console on the top right of the dashboard

### 👟 Reproduction steps

I use Firefox, and just tried to paste my login command, no luck.

### 👀 Expected behavior

For text to be pasted in.

### 😓 Actual Behavior

The text is not pasted

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox 124.0.1

### 🐋 Docker Version

26.0.0

**Comment by louislam** [comment]
https://github.com/louislam/dockge/discussions/141
