### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by bryceprutsos** [louislam/dockge#472]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

In your setup on readme under Basic the 
# Start the server
docker compose up -d

should be 

# Start the server
docker-compose up -d

Thanks for all your hard work

### 👟 Reproduction steps

just running the code

docker compose up -d

### 👀 Expected behavior

should deploy dockge

### 😓 Actual Behavior

if we use the command it just errors out.

### Dockge Version

latest

### 💻 Operating System and Arch

ubunutu

### 🌐 Browser

chrome

### 🐋 Docker Version

lastest

**Comment by louislam** [comment]
It is a docker compose v2 command.
