### ISSUE TITLE
docker login does not work via GUI

### ISSUE THREAD

**Issue by p10tyr** [louislam/dockge#487]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When I use the GUI bash terminal to do docker login and enter my username. It says `command is not allowed` ?

I log in with SSH and do docker login, authenticated OK.

Press start on stack

### 👟 Reproduction steps

- Add a private image in stack
- docker login in GUI does not work
- docker login in SSH - Authenticated OK
- start stack
- error

`Error response from daemon: pull access denied for private-reop/cool-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

pull in ssh - pulled OK

### 👀 Expected behavior

image is pulled in GUI after login in SSH

### 😓 Actual Behavior

`Error response from daemon: pull access denied for private-reop/cool-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

### Dockge Version

latest

### 💻 Operating System and Arch

debian

### 🌐 Browser

edge

### 🐋 Docker Version

latest

### 📝 Relevant log output

```shell
`Error response from daemon: pull access denied for private-reop/cool-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`
```

**Comment by Nick390** [comment]
Where I can find `dockage/compose.yml` ?
