### ISSUE TITLE
This stack is not managed by Dockge

### ISSUE THREAD

**Issue by fragolinux** [louislam/dockge#509]
please delete, solved

**Comment by eithe** [comment]
For anyone else coming here; I renamed one of the stack folders (lets say from stack1 to stack2) which caused stack1 to still show in Dockge as "not managed". To delete it from Dockge, I just created a new folder with the name stack1, and put a dummy compose.yaml file inside. Then I went back to Dockge, pressed Scan Stacks Folder, refreshed the page, and then I was able to delete stack1 from Dockge.

**Comment by xpufx** [comment]
> For anyone else coming here; I renamed one of the stack folders (lets say from stack1 to stack2) which caused stack1 to still show in Dockge as "not managed". To delete it from Dockge, I just created a new folder with the name stack1, and put a dummy compose.yaml file inside. Then I went back to Dockge, pressed Scan Stacks Folder, refreshed the page, and then I was able to delete stack1 from Dockge.

you can docker rm the existing container and delete the directory
