### ISSUE TITLE
It's not possible to delete a stack

### ISSUE THREAD

**Issue by bramvdzee** [louislam/dockge#52]
I've tried this twice now, but every time I try to delete a stack it gives the following message:

![image](https://github.com/louislam/dockge/assets/6660590/69730751-9557-435a-a004-2030e892f882)

Simply stopping the containers and deleting the compose.yml file results in a dangling stack that cannot be removed, as it is 'not managed by Dockge'.

**Comment by louislam** [comment]
Just released 1.0.4, it should be fixed.
