### ISSUE TITLE
Useless scrollbar on the Terminal

### ISSUE THREAD

**Issue by RotaN8** [louislam/dockge#563]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I have found a possible error with the CSS of Dockge Web UI:

https://github.com/louislam/dockge/blob/109222f0248e17935db439d2db0eb421194007da/frontend/src/components/Terminal.vue#L250

### 👟 Reproduction steps

It's always present.

### 👀 Expected behavior

![20240707_22h53m59s_grim](https://github.com/louislam/dockge/assets/61917364/7bbc04dd-474e-4072-8828-565e40a8e890)
![20240707_22h54m32s_grim](https://github.com/louislam/dockge/assets/61917364/a840442f-550b-4802-9564-981edea76398)

As you can see at the image when the `overflow-x: scroll` is NOT present the useless scrollbar disappears.

### 😓 Actual Behavior

![20240707_22h51m25s_grim](https://github.com/louislam/dockge/assets/61917364/09230524-d813-4266-975b-39f501ea69d6)
![20240707_22h52m43s_grim](https://github.com/louislam/dockge/assets/61917364/b8a51c03-1d2d-43c3-bff4-d71b520b267a)

As you can see at the image when the `overflow-x: scroll` is present a useless scrollbar appears at the right.

### Dockge Version

1.4.2

### 💻 Operating System and Arch

ArchLinux x64

### 🌐 Browser

Brave 1.67.123 (Chromium: 126.0.6478.126) (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 27.0.3

**Comment by Areopagitics** [comment]
I understand the scrollbar was not working, but now there is no way to see longer command outputs, or reports. Is there no way to fix the scrollbar so that we can see previous terminal output.

I think this is a pretty important feature. Think about it.
