### ISSUE TITLE
Dockge is restarting in loop

### ISSUE THREAD

**Issue by Parlendir** [louislam/dockge#564]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Hi

I'm trying to run Dockge and got this error in the logs : 

the container is restarting in a loop.

I've found this other issue which was not answered du to an invalid format :  cannot run #499 : https://github.com/louislam/dockge/issues/499

### 👟 Reproduction steps

i did nothing special : 
- took the compose.yaml from https://dockge.kuma.pet/
- followed the steps indicated and didn't change any folder

### 👀 Expected behavior

container running fine.

### 😓 Actual Behavior

container reboots in a loop

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian 5.10.197-1

### 🌐 Browser

firefox latest

### 🐋 Docker Version

20.10.6

### 📝 Relevant log output

```shell
node[8]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb83f50 node::Abort() [node]
 2: 0xb83fce  [node]
 3: 0xbf14ee  [node]
 4: 0xbf15d1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb41ed3 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb4256b node::Start(int, char**) [node]
 7: 0x7f331bc271ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f331bc27285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xac1fee _start [node]
bash: line 1:     8 Aborted                 (core dumped) node ./extra/clean-tsx-tmp.js
```

**Comment by louislam** [comment]
> ❌ Debian/Raspbian Buster or lower is not supported
